---
title: "IST772– Week9 Async"
author: "Sathish Kumar Rajendiran"
output: pdf_document
---


```{r}
exp(1)
exp(0)
exp(2)
exp(-1)
```

```{r}
# First, define this custom logistic function by running these three lines of code:

logistic <- function(logistX)
{
  exp(logistX)/(exp(logistX)+1)
}


logistic(3)
# 0.9525741

logistic(6)
```
```{r}
set.seed(123)
logistX <- rnorm(n=100,mean=0,sd=1)
logistY <- exp(logistX)/exp(logistX)+1
binomY <- round(logistY)

logistX <- logistX/1.41 +rnorm(n=100,mean=0,sd=1)/1.41
binomY <- factor(round(logistY),labels(c('Truth','Lie')))
logistDF <- data.frame(logistX,logistY,binomY)

boxplot(formula=logistX ~ binomY, data=logistDF,ylab="GSR",main=NULL)
```
```{r}
set.seed(1234)
logistX <- rnorm(n=1000,mean=0,sd=1)
binomY <- round(exp(logistX)/(exp(logistX)+1))
logistX <- logistX/1.41 + rnorm(n=1000,mean=0,sd=1)/1.41
glmOut <- glm(binomY ~ logistX, family=binomial())
summary(glmOut)
anova(glmOut, test="Chisq")
```

```{r}
set.seed(1234)
logistX <- rnorm(n=1000,mean=0,sd=1)
binomY <- round(exp(logistX)/(exp(logistX)+1))
logistX <- logistX/1.41 + rnorm(n=1000,mean=0,sd=1)/1.41
glmOut <- glm(binomY ~ logistX, family=binomial())
summary(glmOut)
anova(glmOut, test="Chisq")
exp(coef(glmOut))
```
```{r}

x =  1.278e-02
x

y = 2.584e-02
y
```

```{r}
install.packages("car") # Regression helper package: Chile data
install.packages("MCMCpack")    # Download MCMCpack package

library(car)
data(Chile)
ChileY <- Chile[Chile$vote == "Y",] # Grab the Yes votes
ChileN <- Chile[Chile$vote == "N",] # Grab the No votes
ChileYN <- rbind(ChileY,ChileN) # Make a new dataset with those
ChileYN <- ChileYN[complete.cases(ChileYN),] # Get rid of missing
ChileYN$vote <- factor(ChileYN$vote,levels=c("N","Y")) # Fix the factor
ChileYN$age10 <- ChileYN$age/10

library(MCMCpack) # Load the package
ChileYN$vote <- as.numeric(ChileYN$vote) - 1 # Adjust the outcome
set.seed(271) # Control randomization
bayesLogitOut <- MCMClogit(formula = vote ~ age10 + income, data = ChileYN)
summary(bayesLogitOut) # Summarize the results

ageLogOdds <- as.matrix(bayesLogitOut[,"age10"])
ageOdds <- apply(ageLogOdds,1,exp) # Transform with exp()
mean(ageOdds) # The point estimate for age/10 in plain odds
quantile(ageOdds,c(0.025)) # Lower bound of HDI
quantile(ageOdds,c(0.975)) # Upper bound of HDI
```
```{r}

ChileYN$age10 <- ChileYN$age/10
glmOut <- glm(binomY ~ logistX, family=binomial())
summary(glmOut)

chout <- glm(formula = vote ~ ChileYN$age10+income,family = binomial(),data=ChileYN)
summary(chout)
```
```{r}
# EnsurePackage("MASS") # AIC

stepOut <- stepAIC(chout)
stepOut$anova
```

