---
title: "R Notebook"
output: html_notebook
---
----------------------------------------------------------------------------------
Title: "IST772 Week 3 – Sampling Exercise #1"
Name: Sathish Kumar Rajendiran
Date: 10/16/2020
-----------------------------------------------------------------------------------



```{r}
set.seed(1234)                                        # Control randomization
testPop <- rnorm(100000, mean=100, sd=10)             # Create simulated population 
testPopMean <- mean(testPop)                          # Calculate mean
sumSq <- sum((testPop-testPopMean)^2)                 # Sum of squares
testPopVar <- sumSq/length(testPop)                   # Variance
testPopSD <- sqrt(testPopVar)                         # Standard deviation
```

```{r}
hist(testPop)
```
```{r}
# Markings of quartiles
hist(testPop)                                           
abline(v=quantile(testPop, probs=0.25),col="orange")    # First quartile
abline(v=quantile(testPop, probs=0.5),col="blue")     # Second quartile
abline(v=quantile(testPop, probs=0.75),col="red")    # Third quartile

```
```{r}
# Markings of one and two standard deviations 
hist(testPop)
abline(v=90, col="red")
abline(v=80, col="blue")
abline(v=110, col="red") 
abline(v=120, col="blue")
```

```{r}
# Markings of the central region and tails 
hist(testPop)
abline(v=quantile(testPop, probs=0.025),col="green") 
abline(v=quantile(testPop, probs=0.975),col="green")

```

